spring:
  application:
    name: proxy-spring

server:
  port: 8080

file:
#  path: F:\\OneDrive - for personal\\Entertainment\\changfeng\\blogback.txt
  path: /root/proxy/blog.txt


proxy:
  size: 100
